api = "0.7"

[buildpack]
  description = "A buildpack for starting a puma server for a Ruby app"
  homepage = "https://github.com/paketo-buildpacks/puma"
  id = "paketo-buildpacks/puma"
  version = "0.4.60"
  keywords = ["ruby", "puma"]
  name = "Paketo Buildpack for Puma"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/puma/blob/main/LICENSE"

[metadata]
  include-files = [
    "buildpack.toml",
    "linux/amd64/bin/run",
    "linux/amd64/bin/build",
    "linux/amd64/bin/detect",
    "linux/arm64/bin/run",
    "linux/arm64/bin/build",
    "linux/arm64/bin/detect",
  ]
  pre-package = "./scripts/build.sh"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"

[[stacks]]
  id = "*"
